[2025-05-11T03:57:39.128+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T03:57:39.177+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T03:57:39.189+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T03:57:39.190+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-11T03:57:39.213+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_lstm_dbt> on 2025-05-08 11:30:00+00:00
[2025-05-11T03:57:39.227+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bbca_lstm_prediction', 'run_lstm_dbt', 'scheduled__2025-05-08T11:30:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/stock_predictions_bbca.py', '--cfg-path', '/tmp/tmp8giehh9m']
[2025-05-11T03:57:39.232+0700] {standard_task_runner.py:91} INFO - Job 105: Subtask run_lstm_dbt
[2025-05-11T03:57:39.245+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1757) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T03:57:39.246+0700] {standard_task_runner.py:63} INFO - Started process 1774 to run task
[2025-05-11T03:57:39.332+0700] {task_command.py:426} INFO - Running <TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [running]> on host a61c3a2f78e1
[2025-05-11T03:57:39.468+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bbca_lstm_prediction' AIRFLOW_CTX_TASK_ID='run_lstm_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T11:30:00+00:00'
[2025-05-11T03:57:39.470+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T03:57:39.487+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T03:57:39.488+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select stg_stock_predictions fct_stock_predictions lstm_performance_metrics stock_prediction_dashboard']
[2025-05-11T03:57:39.504+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T03:57:43.018+0700] {subprocess.py:93} INFO - [0m20:57:43  Running with dbt=1.9.4
[2025-05-11T03:57:43.536+0700] {subprocess.py:93} INFO - [0m20:57:43  Registered adapter: postgres=1.9.0
[2025-05-11T03:57:44.992+0700] {subprocess.py:93} INFO - [0m20:57:44  Found 14 models, 3 data tests, 6 sources, 434 macros
[2025-05-11T03:57:45.000+0700] {subprocess.py:93} INFO - [0m20:57:45
[2025-05-11T03:57:45.002+0700] {subprocess.py:93} INFO - [0m20:57:45  Concurrency: 4 threads (target='dev')
[2025-05-11T03:57:45.005+0700] {subprocess.py:93} INFO - [0m20:57:45
[2025-05-11T03:57:45.363+0700] {subprocess.py:93} INFO - [0m20:57:45  1 of 4 START sql view model public_staging.stg_stock_predictions ............... [RUN]
[2025-05-11T03:57:45.642+0700] {subprocess.py:93} INFO - [0m20:57:45  1 of 4 OK created sql view model public_staging.stg_stock_predictions .......... [[32mCREATE VIEW[0m in 0.27s]
[2025-05-11T03:57:45.649+0700] {subprocess.py:93} INFO - [0m20:57:45  2 of 4 START sql table model public_core.fct_stock_predictions ................. [RUN]
[2025-05-11T03:57:45.781+0700] {subprocess.py:93} INFO - [0m20:57:45  2 of 4 ERROR creating sql table model public_core.fct_stock_predictions ........ [[31mERROR[0m in 0.13s]
[2025-05-11T03:57:45.793+0700] {subprocess.py:93} INFO - [0m20:57:45  3 of 4 SKIP relation public_analytics.lstm_performance_metrics ................. [[33mSKIP[0m]
[2025-05-11T03:57:45.795+0700] {subprocess.py:93} INFO - [0m20:57:45  4 of 4 SKIP relation public_analytics.stock_prediction_dashboard ............... [[33mSKIP[0m]
[2025-05-11T03:57:45.842+0700] {subprocess.py:93} INFO - [0m20:57:45
[2025-05-11T03:57:45.844+0700] {subprocess.py:93} INFO - [0m20:57:45  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 0.83 seconds (0.83s).
[2025-05-11T03:57:45.960+0700] {subprocess.py:93} INFO - [0m20:57:45
[2025-05-11T03:57:45.962+0700] {subprocess.py:93} INFO - [0m20:57:45  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-05-11T03:57:45.964+0700] {subprocess.py:93} INFO - [0m20:57:45
[2025-05-11T03:57:45.967+0700] {subprocess.py:93} INFO - [0m20:57:45    Database Error in model fct_stock_predictions (models/marts/core/fct_stock_predictions.sql)
[2025-05-11T03:57:45.968+0700] {subprocess.py:93} INFO -   subquery in FROM must have an alias
[2025-05-11T03:57:45.968+0700] {subprocess.py:93} INFO -   LINE 29:     FROM (
[2025-05-11T03:57:45.969+0700] {subprocess.py:93} INFO -                     ^
[2025-05-11T03:57:45.970+0700] {subprocess.py:93} INFO -   HINT:  For example, FROM (SELECT ...) [AS] foo.
[2025-05-11T03:57:45.971+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/core/fct_stock_predictions.sql
[2025-05-11T03:57:45.972+0700] {subprocess.py:93} INFO - [0m20:57:45
[2025-05-11T03:57:45.972+0700] {subprocess.py:93} INFO - [0m20:57:45  Done. PASS=1 WARN=0 ERROR=1 SKIP=2 TOTAL=4
[2025-05-11T03:57:47.750+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-11T03:57:47.751+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T03:57:47.769+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-11T03:57:47.777+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=bbca_lstm_prediction, task_id=run_lstm_dbt, run_id=scheduled__2025-05-08T11:30:00+00:00, execution_date=20250508T113000, start_date=20250510T205739, end_date=20250510T205747
[2025-05-11T03:57:47.802+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 105 for task run_lstm_dbt (Bash command failed. The command returned a non-zero exit code 1.; 1774)
[2025-05-11T03:57:47.822+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T03:57:47.850+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T03:57:47.857+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-11T18:26:08.242+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T18:26:08.299+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T18:26:08.313+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T18:26:08.314+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-05-11T18:26:08.342+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_lstm_dbt> on 2025-05-08 11:30:00+00:00
[2025-05-11T18:26:08.360+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bbca_lstm_prediction', 'run_lstm_dbt', 'scheduled__2025-05-08T11:30:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/stock_predictions_bbca.py', '--cfg-path', '/tmp/tmpv9_hc7vy']
[2025-05-11T18:26:08.364+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11992) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T18:26:08.367+0700] {standard_task_runner.py:91} INFO - Job 171: Subtask run_lstm_dbt
[2025-05-11T18:26:08.367+0700] {standard_task_runner.py:63} INFO - Started process 12023 to run task
[2025-05-11T18:26:08.488+0700] {task_command.py:426} INFO - Running <TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [running]> on host 615e6c656dab
[2025-05-11T18:26:08.695+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bbca_lstm_prediction' AIRFLOW_CTX_TASK_ID='run_lstm_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T11:30:00+00:00'
[2025-05-11T18:26:08.697+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T18:26:08.716+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T18:26:08.717+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select stg_stock_predictions fct_stock_predictions lstm_performance_metrics stock_prediction_dashboard']
[2025-05-11T18:26:08.743+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T18:26:12.796+0700] {subprocess.py:93} INFO - [0m11:26:12  Running with dbt=1.9.4
[2025-05-11T18:26:13.284+0700] {subprocess.py:93} INFO - [0m11:26:13  Registered adapter: postgres=1.9.0
[2025-05-11T18:26:14.478+0700] {subprocess.py:93} INFO - [0m11:26:14  Found 14 models, 3 data tests, 6 sources, 434 macros
[2025-05-11T18:26:14.486+0700] {subprocess.py:93} INFO - [0m11:26:14
[2025-05-11T18:26:14.488+0700] {subprocess.py:93} INFO - [0m11:26:14  Concurrency: 4 threads (target='dev')
[2025-05-11T18:26:14.490+0700] {subprocess.py:93} INFO - [0m11:26:14
[2025-05-11T18:26:14.829+0700] {subprocess.py:93} INFO - [0m11:26:14  1 of 4 START sql view model public_staging.stg_stock_predictions ............... [RUN]
[2025-05-11T18:26:15.099+0700] {subprocess.py:93} INFO - [0m11:26:15  1 of 4 OK created sql view model public_staging.stg_stock_predictions .......... [[32mCREATE VIEW[0m in 0.26s]
[2025-05-11T18:26:15.106+0700] {subprocess.py:93} INFO - [0m11:26:15  2 of 4 START sql table model public_core.fct_stock_predictions ................. [RUN]
[2025-05-11T18:26:16.522+0700] {subprocess.py:93} INFO - [0m11:26:16  2 of 4 OK created sql table model public_core.fct_stock_predictions ............ [[32mSELECT 2[0m in 1.41s]
[2025-05-11T18:26:16.530+0700] {subprocess.py:93} INFO - [0m11:26:16  3 of 4 START sql table model public_analytics.lstm_performance_metrics ......... [RUN]
[2025-05-11T18:26:16.532+0700] {subprocess.py:93} INFO - [0m11:26:16  4 of 4 START sql table model public_analytics.stock_prediction_dashboard ....... [RUN]
[2025-05-11T18:26:16.709+0700] {subprocess.py:93} INFO - [0m11:26:16  3 of 4 OK created sql table model public_analytics.lstm_performance_metrics .... [[32mSELECT 1[0m in 0.17s]
[2025-05-11T18:26:21.728+0700] {subprocess.py:93} INFO - [0m11:26:21  4 of 4 OK created sql table model public_analytics.stock_prediction_dashboard .. [[32mSELECT 53599[0m in 5.19s]
[2025-05-11T18:26:21.813+0700] {subprocess.py:93} INFO - [0m11:26:21
[2025-05-11T18:26:21.816+0700] {subprocess.py:93} INFO - [0m11:26:21  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 7.32 seconds (7.32s).
[2025-05-11T18:26:21.964+0700] {subprocess.py:93} INFO - [0m11:26:21
[2025-05-11T18:26:21.965+0700] {subprocess.py:93} INFO - [0m11:26:21  [32mCompleted successfully[0m
[2025-05-11T18:26:21.967+0700] {subprocess.py:93} INFO - [0m11:26:21
[2025-05-11T18:26:21.969+0700] {subprocess.py:93} INFO - [0m11:26:21  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-05-11T18:26:23.613+0700] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-11T18:26:23.614+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T18:26:23.654+0700] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bbca_lstm_prediction, task_id=run_lstm_dbt, run_id=scheduled__2025-05-08T11:30:00+00:00, execution_date=20250508T113000, start_date=20250511T112608, end_date=20250511T112623
[2025-05-11T18:26:23.687+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-11T18:26:23.708+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T18:26:23.715+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-12T06:26:38.419+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T06:26:38.457+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-12T06:26:38.466+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-12T06:26:38.467+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-12T06:26:38.484+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_lstm_dbt> on 2025-05-08 11:30:00+00:00
[2025-05-12T06:26:38.496+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4553) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T06:26:38.495+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bbca_lstm_prediction', 'run_lstm_dbt', 'scheduled__2025-05-08T11:30:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/stock_predictions_bbca.py', '--cfg-path', '/tmp/tmpt98yircj']
[2025-05-12T06:26:38.498+0700] {standard_task_runner.py:63} INFO - Started process 4562 to run task
[2025-05-12T06:26:38.498+0700] {standard_task_runner.py:91} INFO - Job 153: Subtask run_lstm_dbt
[2025-05-12T06:26:38.576+0700] {task_command.py:426} INFO - Running <TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [running]> on host 84b3813fe61b
[2025-05-12T06:26:38.691+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bbca_lstm_prediction' AIRFLOW_CTX_TASK_ID='run_lstm_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T11:30:00+00:00'
[2025-05-12T06:26:38.692+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T06:26:38.706+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T06:26:38.707+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select stg_stock_predictions fct_stock_predictions lstm_performance_metrics stock_prediction_dashboard']
[2025-05-12T06:26:38.724+0700] {subprocess.py:86} INFO - Output:
[2025-05-12T06:26:41.384+0700] {subprocess.py:93} INFO - [0m23:26:41  Running with dbt=1.9.4
[2025-05-12T06:26:41.769+0700] {subprocess.py:93} INFO - [0m23:26:41  Registered adapter: postgres=1.9.0
[2025-05-12T06:26:42.666+0700] {subprocess.py:93} INFO - [0m23:26:42  Found 14 models, 3 data tests, 6 sources, 434 macros
[2025-05-12T06:26:42.672+0700] {subprocess.py:93} INFO - [0m23:26:42
[2025-05-12T06:26:42.674+0700] {subprocess.py:93} INFO - [0m23:26:42  Concurrency: 4 threads (target='dev')
[2025-05-12T06:26:42.676+0700] {subprocess.py:93} INFO - [0m23:26:42
[2025-05-12T06:26:42.933+0700] {subprocess.py:93} INFO - [0m23:26:42  1 of 4 START sql view model public_staging.stg_stock_predictions ............... [RUN]
[2025-05-12T06:26:43.135+0700] {subprocess.py:93} INFO - [0m23:26:43  1 of 4 OK created sql view model public_staging.stg_stock_predictions .......... [[32mCREATE VIEW[0m in 0.20s]
[2025-05-12T06:26:43.142+0700] {subprocess.py:93} INFO - [0m23:26:43  2 of 4 START sql table model public_core.fct_stock_predictions ................. [RUN]
[2025-05-12T06:26:43.676+0700] {subprocess.py:93} INFO - [0m23:26:43  2 of 4 OK created sql table model public_core.fct_stock_predictions ............ [[32mSELECT 1[0m in 0.53s]
[2025-05-12T06:26:43.683+0700] {subprocess.py:93} INFO - [0m23:26:43  3 of 4 START sql table model public_analytics.lstm_performance_metrics ......... [RUN]
[2025-05-12T06:26:43.685+0700] {subprocess.py:93} INFO - [0m23:26:43  4 of 4 START sql table model public_analytics.stock_prediction_dashboard ....... [RUN]
[2025-05-12T06:26:43.789+0700] {subprocess.py:93} INFO - [0m23:26:43  4 of 4 ERROR creating sql table model public_analytics.stock_prediction_dashboard  [[31mERROR[0m in 0.09s]
[2025-05-12T06:26:43.845+0700] {subprocess.py:93} INFO - [0m23:26:43  3 of 4 OK created sql table model public_analytics.lstm_performance_metrics .... [[32mSELECT 0[0m in 0.16s]
[2025-05-12T06:26:43.883+0700] {subprocess.py:93} INFO - [0m23:26:43
[2025-05-12T06:26:43.884+0700] {subprocess.py:93} INFO - [0m23:26:43  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 1.20 seconds (1.20s).
[2025-05-12T06:26:43.985+0700] {subprocess.py:93} INFO - [0m23:26:43
[2025-05-12T06:26:43.987+0700] {subprocess.py:93} INFO - [0m23:26:43  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-05-12T06:26:43.988+0700] {subprocess.py:93} INFO - [0m23:26:43
[2025-05-12T06:26:43.990+0700] {subprocess.py:93} INFO - [0m23:26:43    Database Error in model stock_prediction_dashboard (models/marts/analytics/stock_prediction_dashboard.sql)
[2025-05-12T06:26:43.991+0700] {subprocess.py:93} INFO -   column m.macd_histogram does not exist
[2025-05-12T06:26:43.991+0700] {subprocess.py:93} INFO -   LINE 28:         m.macd_histogram
[2025-05-12T06:26:43.992+0700] {subprocess.py:93} INFO -                    ^
[2025-05-12T06:26:43.993+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/analytics/stock_prediction_dashboard.sql
[2025-05-12T06:26:43.993+0700] {subprocess.py:93} INFO - [0m23:26:43
[2025-05-12T06:26:43.994+0700] {subprocess.py:93} INFO - [0m23:26:43  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2025-05-12T06:26:45.598+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T06:26:45.599+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T06:26:45.616+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T06:26:45.622+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=bbca_lstm_prediction, task_id=run_lstm_dbt, run_id=scheduled__2025-05-08T11:30:00+00:00, execution_date=20250508T113000, start_date=20250511T232638, end_date=20250511T232645
[2025-05-12T06:26:45.638+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 153 for task run_lstm_dbt (Bash command failed. The command returned a non-zero exit code 1.; 4562)
[2025-05-12T06:26:45.674+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-12T06:26:45.693+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T06:26:45.699+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
