[2025-05-11T04:29:19.700+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T04:29:19.769+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T04:29:19.784+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [queued]>
[2025-05-11T04:29:19.785+0700] {taskinstance.py:2306} INFO - Starting attempt 11 of 12
[2025-05-11T04:29:19.812+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_lstm_dbt> on 2025-05-08 11:30:00+00:00
[2025-05-11T04:29:19.829+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bbca_lstm_prediction', 'run_lstm_dbt', 'scheduled__2025-05-08T11:30:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/stock_predictions_bbca.py', '--cfg-path', '/tmp/tmpjaw75jcl']
[2025-05-11T04:29:19.834+0700] {standard_task_runner.py:91} INFO - Job 115: Subtask run_lstm_dbt
[2025-05-11T04:29:19.845+0700] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1054) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T04:29:19.846+0700] {standard_task_runner.py:63} INFO - Started process 1080 to run task
[2025-05-11T04:29:19.939+0700] {task_command.py:426} INFO - Running <TaskInstance: bbca_lstm_prediction.run_lstm_dbt scheduled__2025-05-08T11:30:00+00:00 [running]> on host 63831b4a45c6
[2025-05-11T04:29:20.083+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bbca_lstm_prediction' AIRFLOW_CTX_TASK_ID='run_lstm_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T11:30:00+00:00'
[2025-05-11T04:29:20.085+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T04:29:20.104+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-11T04:29:20.106+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/dbt --select stg_stock_predictions fct_stock_predictions lstm_performance_metrics stock_prediction_dashboard']
[2025-05-11T04:29:20.123+0700] {subprocess.py:86} INFO - Output:
[2025-05-11T04:29:23.549+0700] {subprocess.py:93} INFO - [0m21:29:23  Running with dbt=1.9.4
[2025-05-11T04:29:24.004+0700] {subprocess.py:93} INFO - [0m21:29:24  Registered adapter: postgres=1.9.0
[2025-05-11T04:29:25.898+0700] {subprocess.py:93} INFO - [0m21:29:25  Found 14 models, 3 data tests, 6 sources, 434 macros
[2025-05-11T04:29:25.906+0700] {subprocess.py:93} INFO - [0m21:29:25
[2025-05-11T04:29:25.908+0700] {subprocess.py:93} INFO - [0m21:29:25  Concurrency: 4 threads (target='dev')
[2025-05-11T04:29:25.910+0700] {subprocess.py:93} INFO - [0m21:29:25
[2025-05-11T04:29:26.256+0700] {subprocess.py:93} INFO - [0m21:29:26  1 of 4 START sql view model public_staging.stg_stock_predictions ............... [RUN]
[2025-05-11T04:29:26.524+0700] {subprocess.py:93} INFO - [0m21:29:26  1 of 4 OK created sql view model public_staging.stg_stock_predictions .......... [[32mCREATE VIEW[0m in 0.26s]
[2025-05-11T04:29:26.532+0700] {subprocess.py:93} INFO - [0m21:29:26  2 of 4 START sql table model public_core.fct_stock_predictions ................. [RUN]
[2025-05-11T04:29:27.234+0700] {subprocess.py:93} INFO - [0m21:29:27  2 of 4 OK created sql table model public_core.fct_stock_predictions ............ [[32mSELECT 1[0m in 0.70s]
[2025-05-11T04:29:27.242+0700] {subprocess.py:93} INFO - [0m21:29:27  3 of 4 START sql table model public_analytics.lstm_performance_metrics ......... [RUN]
[2025-05-11T04:29:27.244+0700] {subprocess.py:93} INFO - [0m21:29:27  4 of 4 START sql table model public_analytics.stock_prediction_dashboard ....... [RUN]
[2025-05-11T04:29:27.383+0700] {subprocess.py:93} INFO - [0m21:29:27  3 of 4 ERROR creating sql table model public_analytics.lstm_performance_metrics  [[31mERROR[0m in 0.13s]
[2025-05-11T04:29:35.689+0700] {subprocess.py:93} INFO - [0m21:29:35  4 of 4 OK created sql table model public_analytics.stock_prediction_dashboard .. [[32mSELECT 53599[0m in 8.44s]
[2025-05-11T04:29:35.732+0700] {subprocess.py:93} INFO - [0m21:29:35
[2025-05-11T04:29:35.734+0700] {subprocess.py:93} INFO - [0m21:29:35  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 9.82 seconds (9.82s).
[2025-05-11T04:29:35.861+0700] {subprocess.py:93} INFO - [0m21:29:35
[2025-05-11T04:29:35.864+0700] {subprocess.py:93} INFO - [0m21:29:35  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-05-11T04:29:35.866+0700] {subprocess.py:93} INFO - [0m21:29:35
[2025-05-11T04:29:35.868+0700] {subprocess.py:93} INFO - [0m21:29:35    Database Error in model lstm_performance_metrics (models/marts/analytics/lstm_performance_metrics.sql)
[2025-05-11T04:29:35.869+0700] {subprocess.py:93} INFO -   syntax error at or near "EOF"
[2025-05-11T04:29:35.870+0700] {subprocess.py:93} INFO -   LINE 65: EOF
[2025-05-11T04:29:35.870+0700] {subprocess.py:93} INFO -            ^
[2025-05-11T04:29:35.871+0700] {subprocess.py:93} INFO -   compiled code at target/run/idx_stock/models/marts/analytics/lstm_performance_metrics.sql
[2025-05-11T04:29:35.872+0700] {subprocess.py:93} INFO - [0m21:29:35
[2025-05-11T04:29:35.873+0700] {subprocess.py:93} INFO - [0m21:29:35  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2025-05-11T04:29:37.518+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-11T04:29:37.520+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T04:29:37.544+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-11T04:29:37.555+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bbca_lstm_prediction, task_id=run_lstm_dbt, run_id=scheduled__2025-05-08T11:30:00+00:00, execution_date=20250508T113000, start_date=20250510T212919, end_date=20250510T212937
[2025-05-11T04:29:37.581+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 115 for task run_lstm_dbt (Bash command failed. The command returned a non-zero exit code 1.; 1080)
[2025-05-11T04:29:37.609+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T04:29:37.640+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T04:29:37.647+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
